### ISSUE TITLE
mvn dependencies fail

### ISSUE THREAD

**Issue by sivareddyg** [syxu828/QuestionAnsweringOverFB#1]
I am trying to download all the dependencies. This is the command I used

> mvn dependency:resolve

 but I get this error. 
> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.480 s
[INFO] Finished at: 2016-07-12T11:08:10+00:00
[INFO] Final Memory: 10M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project QuestionAnsweringOverFB: Could not resolve dependencies for project QuestionAnsweringOverFB:QuestionAnsweringOverFB:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: acemodel:acemodel:jar:1.0, edu:edu.mit.jwi_2.2.6:jar:1.0, EntityComparison:EntityComparison:jar:1.0, google:google-api-spelling-java-1.1:jar:1.0, javatools:javatools:jar:1.0, jaws:jaws-bin:jar:1.0, jbzip2:jbzip2-0.9.1:jar:1.0, LBJChunk:LBJChunk:jar:1.0, LbjNerTagger:LbjNerTagger:jar:1.0, liblinear:liblinear-1.5-with-deps:jar:1.0, lingpipe:lingpipe-4.0.1:jar:1.0, SecondString:SecondString:jar:1.0: Failure to find acemodel:acemodel:jar:1.0 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

How do you compile this at your end?

**Comment by sivareddyg** [comment]
Thanks for pushing the jars. I pulled the current version, and ran this command. 

> java -cp target/classes:target/lib/* Joint_EL_RE.Test

which leads to these errors:

> Exception in thread "main" java.lang.NoClassDefFoundError: edu/pku/wip/RelationExtractor
        at Joint_EL_RE.Test.Joint_Inference(Test.java:106)
        at Joint_EL_RE.Test.main(Test.java:218)
Caused by: java.lang.ClassNotFoundException: edu.pku.wip.RelationExtractor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more

Can you please update here when this is resolved? Thanks!

**Comment by umas** [comment]
Hi, 

I am getting  the same error. Where can I find these jars?

[ERROR] Failed to execute goal on project QuestionAnsweringOverFB: Could not resolve dependencies for project QuestionAnsweringOverFB:QuestionAnsweringOverFB:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: acemodel:acemodel:jar:1.0, edu:edu.mit.jwi_2.2.6:jar:1.0, EntityComparison:EntityComparison:jar:1.0, google:google-api-spelling-java-1.1:jar:1.0, javatools:javatools:jar:1.0, jaws:jaws-bin:jar:1.0, jbzip2:jbzip2-0.9.1:jar:1.0, LBJChunk:LBJChunk:jar:1.0, LbjNerTagger:LbjNerTagger:jar:1.0, liblinear:liblinear-1.5-with-deps:jar:1.0, lingpipe:lingpipe-4.0.1:jar:1.0, SecondString:SecondString:jar:1.0: Could not find artifact acemodel:acemodel:jar:1.0 in clapper-org-maven-repo 

Thanks,
Uma

**Comment by sivareddyg** [comment]
Hi Uma,

Please try this fork https://github.com/sivareddyg/QuestionAnsweringOverFB 

You must be able to run the code now without Maven.

Cheers,
Siva
