### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by sivareddyg** [syxu828/QuestionAnsweringOverFB#2]
Hi Kun, I did not find the current instructions useful to run the code. Can you please update as necessary. Please make sure that you can run the code at your end by cloning a copy.

thanks,
siva

**Comment by syxu828** [comment]
OK Siva, I will make it work today !

Best,
Kun

**Comment by sivareddyg** [comment]
Hi Kun,

My Freebase version can now be downloaded from https://www.dropbox.com/sh/zxv2mos2ujjyxnu/AAACCR4AJ1MMTCe8ElfBN39Ha?dl=0

When you get time after vacation, could you please update README on how to use this Freebase  version (changes required in virtuoso.ini), and run your code.

thanks
siva
