### ISSUE TITLE
Can not run Joint_EL_RE/Test.java

### ISSUE THREAD

**Issue by datnb** [syxu828/QuestionAnsweringOverFB#4]
Hi Kun and Siva,

When running Joint_EL_RE.Test, we got this exception.

java.io.IOException:` Cannot run program
"resources/tool/libsvm-3.20/svm-predict": CreateProcess error=2, The
system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at Joint_EL_RE.FeatureExtractor.computeRegressionScore(FeatureExtractor.java:271)
        at Joint_EL_RE.FeatureExtractor.extractFeatureVector(FeatureExtractor.java:110)

We've already checked that resources/tool/libsvm-3.20/svm-predict does
exist. Any suggestions?

Thanks a lot.

Best,
Dat

**Comment by syxu828** [comment]
Hi Dat, could you please show me how you run this Test.java (i.e., the main function)?

**Comment by datnb** [comment]
Hi Kun,

Here is the main function:
public static void main(String[] args){
        Test test = new Test();
        test.Joint_Inference();
//        test.rewriteAns();

        //we need to perform the inference apporach for the training data to produce the input for the wiki inference step
//        String[] testDecomPaths = {"resources/Train/train.questions.decomposed"};
//        String[] testELPaths = {"resources/Train/train.EL.results"};
//        String[] testQuestionPaths = {"resources/Train/train.questions"};
//        String[] goldQAPaths = {"resources/WebQuestions/train.data", "resources/WebQuestions/dev.data"};
//        String testDataFilePath = "resources/JointInference/Train/joint_inference.predicted.69";
//        String finalResultFilePath = "resources/JointInference/Train/joint_inference.predicted.final";
//        String wikiInferenceInputFilePath = "resources/JointInference/Train/wikiInference.input";
//        Test inference_on_training = new Test(testDecomPaths, testELPaths, testQuestionPaths, goldQAPaths, testDataFilePath, finalResultFilePath, wikiInferenceInputFilePath);
//        inference_on_training.Joint_Inference();

    }

Best,
Dat
